
server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lisonglei?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: lisonglei
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
#  jpa:
#    database: mysql
#    show-sql: true
#    open-in-view: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.songley.entity